# Generated by Django 3.2.7 on 2021-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='user_info_photos/')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('emp_date', models.DateField()),
                ('emp_team', models.IntegerField()),
                ('emp_grade', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
