# Generated by Django 3.2.7 on 2021-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='duties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='off_choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
